search: flag --index, help text, test script

diff --git a/orcli b/orcli
--- a/orcli
+++ b/orcli
@@ -568,7 +568,10 @@ orcli_info_usage() {
 # :command.usage
 orcli_search_usage() {
   if [[ -n $long_usage ]]; then
-    printf "orcli search - apply regex to each column and print matches in flattened tsv format\n"
+    printf "orcli search\n"
+    echo
+
+    printf "  apply regex to each column and print matches in flattened tsv format\n  output: index	column	value\n"
     echo
 
   else
@@ -578,13 +581,19 @@ orcli_search_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  orcli search PROJECT [REGEX]\n"
+  printf "  orcli search PROJECT [REGEX] [OPTIONS]\n"
   printf "  orcli search --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--index COLUMN"
+    printf "    print column values instead of row.index in the first column of the output\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -601,14 +610,15 @@ orcli_search_usage() {
 
     # :argument.usage
     printf "  %s\n" "REGEX"
-    printf "    search\n"
+    printf "    search term (regular expression, case-sensitive)\n"
     echo
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  orcli search \"duplicates\" \"^Ben\"\n"
     printf "  orcli search 1234567890123 \"^Ben\"\n"
-    printf "  orcli search \"duplicates\" \"^Ben\" | column -t -s \$'\t'\n"
+    printf "  orcli search \"duplicates\" \"^F$\" --index \"email\"\n"
+    printf "  orcli search \"duplicates\" | column -t -s \$'\t'\n"
     echo
 
   fi
@@ -1294,7 +1304,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'search\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_orcli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_orcli_completions_filter "--help --index -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'export\'*)'
@@ -1595,14 +1605,23 @@ orcli_search_command() {
   projectid="$(get_id "${args[project]}")"
 
   # set facets config
-  args[facets]="[ { \"type\": \"list\", \"expression\": \"grel:filter(row.columnNames,cn,cells[cn].value.find(/${args[--regex]}/).length()>0).length()>0\", \"columnName\": \"\", \"selection\": [ { \"v\": { \"v\": true } } ] } ]"
+  args['--facets']='[ { "type": "list", "expression": "grel:filter(row.columnNames,cn,cells[cn].value.find(/'
+  args['--facets']+="${args[regex]}"
+  args['--facets']+='/).length()>0).length()>0", "columnName": "", "selection": [ { "v": { "v": true } } ] } ]'
 
   # set template
   template='{{'
   template+='forEach(filter(row.columnNames, cn, cells[cn].value.find(/'
   template+="${args[regex]}"
-  template+='/).length()>0), cn, '
-  template+='(row.record.fromRowIndex + 1) + "\t" + cn + "\t" + '
+  template+='/).length()>0), cn,'
+  if [[ ${args[--index]} ]]; then
+      template+='cells["'
+      template+="${args[--index]}"
+      template+='"].value'
+  else
+      template+='(row.index + 1)'
+  fi
+  template+='+ "\t" + cn + "\t" +'
   template+='forNonBlank(cells[cn].value, v, if(v.contains("	"), if(v.contains('\''"'\''), '\''"'\'' + v.replace('\''"'\'','\''""'\'') + '\''"'\'', '\''"'\'' + v + '\''"'\''), v),"")'
   template+='+ "\n")'
   template+='}}'
@@ -1614,6 +1633,7 @@ orcli_search_command() {
 
   # call post_export function to post data and validate results
   post_export "${data[@]}"
+
 }
 
 # :command.function
@@ -3017,6 +3037,20 @@ orcli_search_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --index)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--index']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--index requires an argument: --index COLUMN" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -3046,7 +3080,7 @@ orcli_search_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['project']+x} ]]; then
-    printf "missing required argument: PROJECT\nusage: orcli search PROJECT [REGEX]\n" >&2
+    printf "missing required argument: PROJECT\nusage: orcli search PROJECT [REGEX] [OPTIONS]\n" >&2
     exit 1
   fi
 
