support ./orcli test

diff --git a/orcli b/orcli
--- a/orcli
+++ b/orcli
@@ -1043,13 +1043,6 @@ orcli_test_command() {
   # src/test_command.sh
   # shellcheck shell=bash disable=SC2154
 
-  # check existence of files
-  if ! [[ -f "tests/help.sh" ]]; then
-      error "Cannot open test files!"
-  fi
-  cd "tests"
-  files=(*.sh)
-
   # locate orcli and OpenRefine
   scriptpath=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
   if [[ -x "${scriptpath}/refine" ]]; then
@@ -1057,6 +1050,13 @@ orcli_test_command() {
   else
       error "OpenRefine's startup script (refine) not found!" "Did you put orcli in your OpenRefine app dir?"
   fi
+
+  # check existence of files
+  if ! [[ -f "tests/help.sh" ]]; then
+      error "Cannot open test files!"
+  fi
+  cd "tests"
+  files=(*.sh)
 
   # create tmp directory
   OPENREFINE_TMPDIR="$(mktemp -d)"
