html-form docs styling and escaping

diff --git a/orcli b/orcli
--- a/orcli
+++ b/orcli
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.13 (https://bashly.dev)
+# This script was generated by bashly 1.3.3 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -26,7 +26,7 @@ orcli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Generate bash completions\n" "completions"
+  printf "  %s   generate bash completions\n" "completions"
   printf "  %s   delete OpenRefine project\n" "delete     "
   printf "  %s   commands to create OpenRefine projects from files or URLs\n" "import     "
   printf "  %s   list projects on OpenRefine server\n" "list       "
@@ -86,9 +86,9 @@ fi
 orcli_completions_usage() {
   if [[ -n $long_usage ]]; then
     printf "orcli completions\n\n"
-    printf "  Generate bash completions\n  Usage: source <(orcli completions)\n\n"
+    printf "  generate bash completions\n  usage: source <(orcli completions)\n\n"
   else
-    printf "orcli completions - Generate bash completions\n\n"
+    printf "orcli completions - generate bash completions\n\n"
   fi
 
   printf "%s\n" "Usage:"
@@ -1580,7 +1580,7 @@ send_completions() {
   echo $'# orcli completion                                         -*- shell-script -*-'
   echo $''
   echo $'# This bash completions script was generated by'
-  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# completely (https://github.com/bashly-framework/completely)'
   echo $'# Modifying it manually is not recommended'
   echo $''
   echo $'_orcli_completions_filter() {'
@@ -1588,23 +1588,45 @@ send_completions() {
   echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
   echo $'  local result=()'
   echo $''
+  echo $'  # words the user already typed (excluding the command itself)'
+  echo $'  local used=()'
+  echo $'  if ((COMP_CWORD > 1)); then'
+  echo $'    used=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")'
+  echo $'  fi'
+  echo $''
   echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    # Completing an option: offer everything (including options)'
   echo $'    echo "$words"'
   echo $''
   echo $'  else'
+  echo $'    # Completing a non-option: offer only non-options,'
+  echo $'    # and don\'t re-offer ones already used earlier in the line.'
   echo $'    for word in $words; do'
-  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'      [[ "${word:0:1}" == "-" ]] && continue'
+  echo $''
+  echo $'      local seen=0'
+  echo $'      for u in "${used[@]}"; do'
+  echo $'        if [[ "$u" == "$word" ]]; then'
+  echo $'          seen=1'
+  echo $'          break'
+  echo $'        fi'
+  echo $'      done'
+  echo $'      ((!seen)) && result+=("$word")'
   echo $'    done'
   echo $''
   echo $'    echo "${result[*]}"'
-  echo $''
   echo $'  fi'
   echo $'}'
   echo $''
   echo $'_orcli_completions() {'
   echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
-  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compwords=()'
+  echo $'  if ((COMP_CWORD > 0)); then'
+  echo $'    compwords=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")'
+  echo $'  fi'
   echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  COMPREPLY=()'
   echo $''
   echo $'  case "$compline" in'
   echo $'    \'export template\'*\'--mode\')'
@@ -5264,6 +5286,8 @@ run() {
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
   initialize
-  run "$@"
+  run "${command_line_args[@]}"
 fi
